# Generated by Django 6.0.1 on 2026-06-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('registros', '0006_cursos_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Nombre del curso'),
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
