# Generated by Django 6.0.1 on 2026-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(verbose_name='Descripción del Curso')),
                ('duracion_horas', models.IntegerField(verbose_name='Duración en Horas')),
                ('imagen', models.ImageField(null=True, upload_to='cursos_fotos', verbose_name='Imagen del Curso')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
    ]
